# Generated by Django 3.2.12 on 2022-02-15 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('unit', models.IntegerField()),
                ('choices', models.ManyToManyField(to='questions.AnswerChoice')),
                ('correct', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='questions.answerchoice')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('questions', models.ManyToManyField(to='questions.Question')),
            ],
        ),
    ]
